config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
  	member do
  		get :following, :followers
  	end
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end

  get "search" => "search#search"
  root 'home#top'
  get 'home/about'
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
    belongs_to :book
    validates :comment,presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/search.rb
class Search < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name,presence: true,length: {maximum: 20, minimum: 2}
  validates :introduction,length: { maximum: 50 }
  has_many :books,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  attachment :profile_image

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:update,:edit]

  def show
    @book = Book.find(params[:id])
    @user= User.new(@current_user)
    @booknew=Book.new
    @comment=BookComment.new
  end

  def index
    @books = Book.all 
    @booknew=Book.new
  end

  def create
    @booknew = Book.new(book_params) 
    @booknew.user_id=current_user.id
    if @booknew.save 
      redirect_to @booknew, notice: "You have creatad book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

  def baria_user
    unless Book.find(params[:id]).user_id == current_user.id
      redirect_to books_path
    end
   end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
        @favorite = current_user.favorites.new(book_id: @book.id)
        @favorite.save
        
    end
    def destroy
    	@book = Book.find(params[:book_id])
        @favorite = current_user.favorites.find_by(book_id: @book.id)
        @favorite.destroy
        
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @content)
  end

  private
  def match(model, content)
    if model == 'user'
      User.where(name: content)
    elsif model == 'book'
      Book.where(title: content)
    end
  end

  def forward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{content}%")
    end
  end

  def backward(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}")
    end
  end

  def partical(model, content)
    if model == 'user'
      User.where("name LIKE ?", "%#{content}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{content}%")
    end
  end

  def search_for(how, model, content)
    case how
    when 'match'
      match(model, content)
    when 'forward'
      forward(model, content)
    when 'backward'
      backward(model, content)
    when 'partical'
      partical(model, content)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:update,:edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user), notice: "You have updated user successfully."
  	else
  		render "edit"
  	end
  end

  def following
      @user  = User.find(params[:id])
      @users = @user.followings
      render 'follows'
  end

  def followers
      @user  = User.find(params[:id])
      @users = @user.followers
      render 'followers'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user?(user)
     user == current_user
  	end
end

app/views/comments/_form.html.erb
<%= form_with(model: [book, comment]) do |f| %>
  <div class="row">
  	<div class="col-sm-12">
	  <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
	</div>
  </div>
	  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/comments/_index.html.erb
<% book.book_comments.each do |book_comment| %>
	<li><%= book_comment.user.name %>：
	<%= book_comment.comment %>

	<% if book_comment.user.id == current_user.id %>
		<%= link_to "削除", book_book_comment_path(book,book_comment), method: :delete %>
	<% end %>
		</li>
<% end %>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: comment.book.comments }) %>")
$("textarea").val('')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/8feb93bdf8.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--ヘッダーの記述-->
    <<header class="navbar navbar-fixed-top navbar-inverse border border-white">
      <div class="container">

        <nav class="nav navbar-nav navbar-left">
          <span>Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <!--if文でサインインとアウト時の表示を変更-->
            <% if user_signed_in? %>
            <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
            <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books' %></li>
            <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
            <% else %>
            <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
            <li><%= link_to ' About', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
            <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
            <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
            <% end %>
          </ul>
        </nav>
      </div>

      <!--検索バー表示 -->
            <% if user_signed_in? %>
            <div class="search-form">
              <%= form_tag(search_path, method: :get) do %>
                <%= text_field_tag 'search[content]' %>
                <%= select_tag 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
                <%= select_tag 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
                <%= submit_tag '検索', class: "btn btn-primary" %>
              <% end %>
              </div>
            <% end %>
    </header>
    <!--ヘッダーの記述-->
    <div class="container">
      <p id="notice"><%= notice %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->

      <%= yield %>

    <footer>
        <div class='row'>
          <div class='col-xs-3 col-xs-offset-9'>
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
    </footer>
   </div>

  </body>
</html>