config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update] do
  	member do
  		get :following, :followers
  	end
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
    collection do
      get :search
    end
  end

  get "search" => "search#search"
  root 'home#top'
  get 'home/about'
 end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:update,:edit]

  def show
    @book = Book.find(params[:id])
    @user= User.new(@current_user)
    @booknew=Book.new
    @comment=BookComment.new
  end

  def index
    @books = Book.all 
    @booknew=Book.new
  end

  def create
    @booknew = Book.new(book_params) 
    @booknew.user_id=current_user.id
    if @booknew.save 
      redirect_to @booknew, notice: "You have creatad book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path, notice: "successfully delete book!"
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

  def baria_user
    unless Book.find(params[:id]).user_id == current_user.id
      redirect_to books_path
    end
   end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
	<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% books.each do |book| %>
				<tr>
					<%= render partial: 'post', locals: { book: book} %>
				
				</tr>
				<% end %>
			</tbody>
    </table>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
<% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= book.errors.count %>errors prohibited this book from being saved:</h2>
          <ul>
             <% book.errors.full_messages.each do |message| %>
               <li><%= message %></li>
             <% end %>
          </ul>
      </div>
 <% end %>
	<div class="field row">
		<%= f.label :Title %>
		<%= f.text_field :title, class: "col-xs-12 book_title form-control is-valid" %>
	</div>

	<div class="field row">
		<%= f.label :Opinion %><!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body form-control is-valid" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/_post.html.erb
<td>
	<%= link_to(book.user) do %>
	<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
	<% end %>
	</td>
	<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
	<td><%= book.body %></td>
	<td id="favorites_buttons_<%= book.id %>">
		<%= render partial: 'favorites/favorite', locals: { book: book} %>
	</td>

 <td>コメント数：<%= book.book_comments.count %></td>

app/views/books/_show.html.erb
<td><%= link_to user_path(book.user.id) do %>
	<%= attachment_image_tag book.user, :profile_image,:fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg",size: "40x40" %><br><%= book.user.name %><% end %>
</td>
<td><%= link_to book.title, book_path(book.id) %></td>
<td><%= book.body %></td>

<td id="favorites_buttons_<%= book.id %>">
	<%= render partial: 'favorites/favorite', locals: { book: book} %>
</td>

<td>コメント数：<%= book.book_comments.count %></td>
<% if book.user.id == current_user.id %>
	<td><%= link_to "Edit", edit_book_path(book.id), class: "btn-sm btn-success edit_book_#{book.id}" %></td>
	<td><%= link_to "Destroy", book_path, class: "btn-sm btn-danger destroy_book_#{book.id}" , method: :delete, data: {confirm: "本当に消しますか?"} %></td>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @booknew %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<%= render 'index', books: @books%>
		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile',user: @book.user %>

		<h2>New book</h2>
		<%= render 'books/newform',book: @booknew %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class='table'>
	      <tr>
			
			<%= render partial: 'show', locals: { book: @book} %>

		  </tr>
		</table>

		<ul id="comments_area">
			<%= render partial: 'comments/index', locals: { book: @book} %>

			<%= render partial: 'comments/form', locals: { book: @book,comment: @comment} %>

        </ul>
	</div>

</div>